const path = require('path');
const webpack = require('webpack');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');

const { entry, output, resolve, module: { rules }, plugins, views, paths } = require('./base');
const viewData = require(path.join(paths.view, '/data.json'));

const appendRules = [
  {
    test: /\.vue$/,
    loader: 'vue-loader',
    options: {
      extractCSS: true
    },
  },
  {
    test: /\.css$/,
    use: ExtractTextPlugin.extract({
      fallback: 'style-loader',
      use: [
        {
          loader: 'css-loader',
          options: {
            importLoaders: 1
          }
        },
        'postcss-loader',
      ],
    }),
  },
];

module.exports = {
  entry,
  output,
  resolve,
  plugins: [
    ...plugins,
    new CopyWebpackPlugin(
      [{ from: paths.assets }],
      { ignore: [
        '.DS_Store',
        'vendor-manifest.json',
      ] }
    ),
    new ExtractTextPlugin('css/[name].css'),
    ...views.map(({ template, filename }) => new HtmlWebpackPlugin({
      template,
      filename: `${filename}.html`,
      inject: false,
      minify: {
        html5: true,
        includeAutoGeneratedTags: true,
        collapseWhitespace: true
      },
      conf: Object.assign({ viewPath: paths.view, isProduction: true }, viewData.common, viewData[filename] ? viewData[filename] : {}),
    })),
    new webpack.optimize.UglifyJsPlugin(),
  ],
  module: {
    rules: [...rules, ...appendRules],
  },
};

